/* ===== GYMTRACKER V02 — Data & Constants ===== */

const EXERCISES = [
    {id:'curl-biceps',zone:'brazos',name_es:'Curl de Bíceps',name_it:'Curl Bicipiti',desc_es:'Flexión de brazos con mancuernas',desc_it:'Flessione delle braccia con manubri',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'extension-triceps',zone:'brazos',name_es:'Extensión de Tríceps',name_it:'Estensione Tricipiti',desc_es:'Extensión de brazos con mancuerna',desc_it:'Estensione delle braccia con manubrio',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'curl-martillo',zone:'brazos',name_es:'Curl Martillo',name_it:'Curl Martello',desc_es:'Curl con agarre neutro',desc_it:'Curl con presa neutra',sets:3,reps:10,equip:['mancuerna'],loc:['casa','gym']},
    {id:'kickback-triceps',zone:'brazos',name_es:'Kickback de Tríceps',name_it:'Kickback Tricipiti',desc_es:'Extensión atrás con mancuerna',desc_it:'Estensione indietro con manubrio',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'curl-concentrado',zone:'brazos',name_es:'Curl Concentrado',name_it:'Curl Concentrato',desc_es:'Curl sentado con apoyo',desc_it:'Curl seduto con supporto',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'press-pecho',zone:'pecho',name_es:'Press de Pecho',name_it:'Panca Pettorali',desc_es:'Presión horizontal de pecho',desc_it:'Pressione orizzontale del petto',sets:4,reps:10,equip:['mancuerna'],loc:['casa','gym']},
    {id:'apertura-mancuernas',zone:'pecho',name_es:'Apertura con Mancuernas',name_it:'Apertura con Manubri',desc_es:'Movimiento de apertura pectoral',desc_it:'Movimento di apertura pettorale',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'press-inclinado',zone:'pecho',name_es:'Press Inclinado',name_it:'Panca Inclinata',desc_es:'Presión de pecho superior',desc_it:'Pressione del petto superiore',sets:3,reps:10,equip:['mancuerna','barra'],loc:['casa','gym']},
    {id:'pullover',zone:'pecho',name_es:'Pullover',name_it:'Pullover',desc_es:'Tracción pectoral',desc_it:'Trazione pettorale',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'floor-press',zone:'pecho',name_es:'Floor Press',name_it:'Floor Press',desc_es:'Presión en el suelo',desc_it:'Pressione sul pavimento',sets:3,reps:10,equip:['mancuerna'],loc:['casa','gym']},
    {id:'russian-twist',zone:'abdomen',name_es:'Russian Twist',name_it:'Russian Twist',desc_es:'Torsión rusa con peso',desc_it:'Torsione russa con peso',sets:3,reps:15,equip:['cuerpo','mancuerna'],loc:['casa','gym']},
    {id:'crunch-peso',zone:'abdomen',name_es:'Crunch con Peso',name_it:'Crunch con Peso',desc_es:'Contracción abdominal con mancuerna',desc_it:'Contrazione addominale con manubrio',sets:3,reps:15,equip:['mancuerna'],loc:['casa','gym']},
    {id:'plancha-remo',zone:'abdomen',name_es:'Plancha con Remo',name_it:'Plank con Remata',desc_es:'Plancha con remo',desc_it:'Plank con remata',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'woodchop',zone:'abdomen',name_es:'Woodchop',name_it:'Woodchop',desc_es:'Torsión diagonal con peso',desc_it:'Torsione diagonale con peso',sets:3,reps:12,equip:['mancuerna','liga'],loc:['casa','gym']},
    {id:'dead-bug',zone:'abdomen',name_es:'Dead Bug con Peso',name_it:'Dead Bug con Peso',desc_es:'Escarabajo muerto con peso',desc_it:'Scarabeo morto con peso',sets:3,reps:12,equip:['cuerpo'],loc:['casa','gym']},
    {id:'sentadilla-sumo',zone:'gluteo',name_es:'Sentadilla Sumo',name_it:'Squat Sumo',desc_es:'Sentadilla con postura sumo',desc_it:'Squat con postura sumo',sets:4,reps:12,equip:['mancuerna','kettlebell'],loc:['casa','gym']},
    {id:'hip-thrust',zone:'gluteo',name_es:'Hip Thrust',name_it:'Hip Thrust',desc_es:'Empuje de cadera con peso',desc_it:'Spinta dell\'anca con peso',sets:4,reps:12,equip:['barra','mancuerna'],loc:['casa','gym']},
    {id:'peso-muerto-rumano',zone:'gluteo',name_es:'Peso Muerto Rumano',name_it:'Stacco Rumeno',desc_es:'Bisagra de cadera',desc_it:'Cerniera dell\'anca',sets:3,reps:10,equip:['mancuerna','barra'],loc:['casa','gym']},
    {id:'step-up',zone:'gluteo',name_es:'Step Up',name_it:'Step Up',desc_es:'Subida a plataforma',desc_it:'Salita su piattaforma',sets:3,reps:12,equip:['mancuerna','cuerpo'],loc:['casa','gym']},
    {id:'puente-gluteo',zone:'gluteo',name_es:'Puente de Glúteo',name_it:'Ponte Glutei',desc_es:'Elevación de cadera en puente',desc_it:'Sollevamento dell\'anca a ponte',sets:3,reps:15,equip:['cuerpo'],loc:['casa','gym']},
    {id:'sentadilla-goblet',zone:'piernas',name_es:'Sentadilla Goblet',name_it:'Squat Goblet',desc_es:'Sentadilla con mancuerna frontal',desc_it:'Squat con manubrio frontale',sets:3,reps:12,equip:['mancuerna','kettlebell'],loc:['casa','gym']},
    {id:'zancada',zone:'piernas',name_es:'Zancada',name_it:'Affondi',desc_es:'Paso adelante con peso',desc_it:'Passo avanti con peso',sets:3,reps:10,equip:['mancuerna','cuerpo'],loc:['casa','gym']},
    {id:'sentadilla-bulgara',zone:'piernas',name_es:'Sentadilla Búlgara',name_it:'Squat Bulgaro',desc_es:'Sentadilla con pie elevado',desc_it:'Squat con piede elevato',sets:3,reps:12,equip:['mancuerna','cuerpo'],loc:['casa','gym']},
    {id:'elevacion-talones',zone:'piernas',name_es:'Elevación de Talones',name_it:'Sollevamento Polpacci',desc_es:'Movimiento de pantorrilla',desc_it:'Movimento del polpaccio',sets:3,reps:15,equip:['mancuerna','cuerpo'],loc:['casa','gym']},
    {id:'peso-muerto',zone:'piernas',name_es:'Peso Muerto',name_it:'Stacco da Terra',desc_es:'Movimiento completo tren inferior',desc_it:'Movimento completo treno inferiore',sets:3,reps:8,equip:['barra','mancuerna'],loc:['casa','gym']},
    {id:'press-hombro',zone:'hombros',name_es:'Press de Hombro',name_it:'Press Spalle',desc_es:'Presión vertical con mancuernas',desc_it:'Pressione verticale con manubri',sets:3,reps:10,equip:['mancuerna','barra'],loc:['casa','gym']},
    {id:'elevacion-lateral',zone:'hombros',name_es:'Elevación Lateral',name_it:'Alzate Laterali',desc_es:'Elevación lateral de brazos',desc_it:'Sollevamento laterale delle braccia',sets:3,reps:12,equip:['mancuerna','liga'],loc:['casa','gym']},
    {id:'elevacion-frontal',zone:'hombros',name_es:'Elevación Frontal',name_it:'Alzate Frontali',desc_es:'Elevación frontal con mancuernas',desc_it:'Sollevamento frontale con manubri',sets:3,reps:12,equip:['mancuerna','liga'],loc:['casa','gym']},
    {id:'pajaro',zone:'hombros',name_es:'Pájaro (Rear Delt Fly)',name_it:'Alzate Posteriori',desc_es:'Elevación posterior inclinado',desc_it:'Sollevamento posteriore piegato',sets:3,reps:12,equip:['mancuerna','liga'],loc:['casa','gym']},
    {id:'encogimiento',zone:'hombros',name_es:'Encogimiento de Hombros',name_it:'Scrollate',desc_es:'Encogimiento de trapecios',desc_it:'Scrollate per trapezi',sets:3,reps:15,equip:['mancuerna','barra'],loc:['casa','gym']},
    {id:'remo-inclinado',zone:'espalda',name_es:'Remo Inclinado',name_it:'Rematore Piegato',desc_es:'Remo con mancuernas inclinado',desc_it:'Rematore con manubri piegato',sets:4,reps:10,equip:['mancuerna','barra'],loc:['casa','gym']},
    {id:'remo-unilateral',zone:'espalda',name_es:'Remo Unilateral',name_it:'Rematore Unilaterale',desc_es:'Remo con un brazo apoyado',desc_it:'Rematore con un braccio appoggiato',sets:3,reps:10,equip:['mancuerna'],loc:['casa','gym']},
    {id:'pullover-espalda',zone:'espalda',name_es:'Pullover para Espalda',name_it:'Pullover per Dorsali',desc_es:'Pullover enfocado en dorsal',desc_it:'Pullover focalizzato sui dorsali',sets:3,reps:12,equip:['mancuerna'],loc:['casa','gym']},
    {id:'remo-t',zone:'espalda',name_es:'Remo en T',name_it:'Rematore a T',desc_es:'Remo con agarre cerrado',desc_it:'Rematore con presa stretta',sets:3,reps:10,equip:['barra','mancuerna'],loc:['casa','gym']},
    {id:'superman-peso',zone:'espalda',name_es:'Superman con Peso',name_it:'Superman con Peso',desc_es:'Extensión lumbar con mancuerna',desc_it:'Estensione lombare con manubrio',sets:3,reps:12,equip:['cuerpo','mancuerna'],loc:['casa','gym']},
];

const ZONES = {
    brazos: {es:'Brazos', it:'Braccia'},
    pecho: {es:'Pecho', it:'Petto'},
    hombros: {es:'Hombros', it:'Spalle'},
    espalda: {es:'Espalda', it:'Schiena'},
    abdomen: {es:'Abdomen', it:'Addome'},
    gluteo: {es:'Glúteo/Cadera', it:'Glutei/Fianchi'},
    piernas: {es:'Piernas', it:'Gambe'}
};

const GOAL_OPTIONS = {
    es: ['Tonificar','Aumentar','Adelgazar','Mantener'],
    it: ['Tonificare','Aumentare','Dimagrire','Mantenere']
};

const i18n = {
    es: {
        'google-btn-text':'Regístrate con Google','w-subtitle':'Entrena inteligentemente, progresa constantemente',
        'ob-next':'Siguiente','ob-start':'Comenzar Entrenamiento',
        's1-title':'Cuéntanos Sobre Ti','s1-gender':'Género','s1-female':'Mujer','s1-male':'Hombre',
        's1-height':'Altura (cm)','s1-weight':'Peso actual (kg)','s1-target':'Peso objetivo (kg)',
        'loc-title':'¿Dónde Entrenas?','loc-casa':'En Casa','loc-gym':'En el Gimnasio',
        'loc-casa-desc':'Entreno con equipo propio','loc-gym-desc':'Tengo acceso a todo el equipo',
        'equip-title':'¿Qué Equipo Tienes?','equip-subtitle':'Selecciona todo el equipo disponible',
        'equip-cuerpo':'Solo Cuerpo','equip-mancuerna':'Mancuernas','equip-liga':'Ligas/Bandas',
        'equip-kettlebell':'Kettlebell','equip-barra':'Barra+Discos','equip-maquina':'Máquinas',
        'select-equip':'Selecciona al menos un equipo','location':'Lugar','equipment-label':'Equipo',
        's2-title':'¿Cuántos Días a la Semana?','s2-days':'días',
        's3-title':'¿Qué Días Entrenas?',
        'day-names':['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
        's4-title':'Objetivos por Zona','s5-title':'Tu Plan Personalizado',
        'bmi':'IMC','height':'Altura','weight':'Peso','target-weight':'Peso objetivo',
        'calories':'Calorías diarias','protein':'Proteínas','water':'Agua','freq-days':'Días/semana',
        'hello':'Hola','this-week':'Esta Semana','streak':'Racha',
        'today-focus':'Entrenamiento de Hoy','exercises':'ejercicios',
        'rest-day':'Día de Descanso','rest-msg':'Tu cuerpo necesita recuperarse. ¡Descansa y vuelve con fuerza!',
        'week-cal':'Esta Semana','start-workout':'Iniciar Entreno',
        'sets':'series','reps':'reps',
        'prog-label':'Estadísticas','prog-t1':'Tu','prog-t2':'Evolución',
        'consistency':'Consistencia','of-planned':'de entrenamientos planificados',
        'personal-records':'Récords Personales','no-records':'Empieza tu primer entrenamiento',
        'logged-as':'Conectado como','current-profile':'Datos Personales','gender':'Género',
        'body-measurements':'Medidas Corporales',
        'chest':'Pecho (cm)','waist':'Cintura (cm)','hips':'Cadera (cm)','thighs':'Muslos (cm)',
        'save':'Guardar Medidas','language':'Idioma',
        'logout':'Cerrar Sesión','reset':'Reiniciar App',
        'reset-title':'Reiniciar App','reset-msg':'¿Estás seguro? Esto eliminará todos tus datos.',
        'saved-msg':'Medidas guardadas','fill-all':'Por favor, completa todos los campos',
        'select-freq':'Selecciona una frecuencia','select-days':'Selecciona {n} días',
        'select-goals':'Selecciona un objetivo para cada zona',
        's6-title':'Medidas Corporales','s6-skip':'Este paso es opcional. Puedes completarlo después en tu perfil.',
        'actual-reps':'Repeticiones realizadas','actual-weight':'Peso utilizado (kg)',
        'next-exercise':'Siguiente Ejercicio','complete-workout':'Completar Entreno',
        'workout-done':'¡Entrenamiento Completado!','celebrate-msg':'¡Excelente trabajo! Has completado tu rutina de hoy.',
        'workout-already-done':'Entrenamiento Completado ✓','back-dash':'Volver al Dashboard',
        'nav-dash':'Home','nav-train':'Entreno','nav-prog':'Progreso','nav-prof':'Perfil',
        'start-timer':'Iniciar','pause-timer':'Pausar',
        'no-workout':'Inicia un entrenamiento desde el Dashboard',
        'nutrition':'Nutrición Recomendada','bmi-section':'Composición Corporal',
        'bmi-low':'Bajo','bmi-normal':'Normal','bmi-over':'Sobrepeso','bmi-obese':'Obeso',
        'female':'Mujer','male':'Hombre',
        'change-routine':'Cambiar rutina de hoy',
        'rest-title':'Descanso','rest-choose':'¿Cuánto descansas?','skip-rest':'Saltar descanso',
        'reconfig-btn':'Reconfigurar Mi Plan','reconfig-title':'Reconfigurar Plan',
        'reconfig-msg':'Esto te permite cambiar ubicación, equipo, frecuencia, días y objetivos. Tu historial y medidas se mantienen.',
        'next-workout':'Próximo Entreno'
    },
    it: {
        'google-btn-text':'Registrati con Google','w-subtitle':'Allenati in modo intelligente, progredisci costantemente',
        'ob-next':'Avanti','ob-start':'Inizia Allenamento',
        's1-title':'Parlaci di Te','s1-gender':'Genere','s1-female':'Donna','s1-male':'Uomo',
        's1-height':'Altezza (cm)','s1-weight':'Peso attuale (kg)','s1-target':'Peso obiettivo (kg)',
        'loc-title':'Dove Ti Alleni?','loc-casa':'A Casa','loc-gym':'In Palestra',
        'loc-casa-desc':'Mi alleno con attrezzatura propria','loc-gym-desc':'Ho accesso a tutta l\'attrezzatura',
        'equip-title':'Che Attrezzatura Hai?','equip-subtitle':'Seleziona tutta l\'attrezzatura disponibile',
        'equip-cuerpo':'Solo Corpo','equip-mancuerna':'Manubri','equip-liga':'Elastici/Bande',
        'equip-kettlebell':'Kettlebell','equip-barra':'Bilanciere+Dischi','equip-maquina':'Macchine',
        'select-equip':'Seleziona almeno un\'attrezzatura','location':'Luogo','equipment-label':'Attrezzatura',
        's2-title':'Quanti Giorni a Settimana?','s2-days':'giorni',
        's3-title':'Quali Giorni Ti Alleni?',
        'day-names':['Dom','Lun','Mar','Mer','Gio','Ven','Sab'],
        's4-title':'Obiettivi per Zona','s5-title':'Il Tuo Piano Personalizzato',
        'bmi':'IMC','height':'Altezza','weight':'Peso','target-weight':'Peso obiettivo',
        'calories':'Calorie giornaliere','protein':'Proteine','water':'Acqua','freq-days':'Giorni/settimana',
        'hello':'Ciao','this-week':'Questa Settimana','streak':'Serie',
        'today-focus':'Allenamento di Oggi','exercises':'esercizi',
        'rest-day':'Giorno di Riposo','rest-msg':'Il tuo corpo ha bisogno di recuperare. Riposa e torna più forte!',
        'week-cal':'Questa Settimana','start-workout':'Inizia Allenamento',
        'sets':'serie','reps':'reps',
        'prog-label':'Statistiche','prog-t1':'La Tua','prog-t2':'Evoluzione',
        'consistency':'Costanza','of-planned':'di allenamenti pianificati',
        'personal-records':'Record Personali','no-records':'Inizia il tuo primo allenamento',
        'logged-as':'Connesso come','current-profile':'Dati Personali','gender':'Genere',
        'body-measurements':'Misure Corporee',
        'chest':'Petto (cm)','waist':'Vita (cm)','hips':'Fianchi (cm)','thighs':'Cosce (cm)',
        'save':'Salva Misure','language':'Lingua',
        'logout':'Disconnetti','reset':'Ripristina App',
        'reset-title':'Ripristina App','reset-msg':'Sei sicuro? Questo eliminerà tutti i tuoi dati.',
        'saved-msg':'Misure salvate','fill-all':'Per favore, compila tutti i campi',
        'select-freq':'Seleziona una frequenza','select-days':'Seleziona {n} giorni',
        'select-goals':'Seleziona un obiettivo per ogni zona',
        's6-title':'Misure Corporee','s6-skip':'Questo passaggio è facoltativo. Puoi completarlo dopo nel tuo profilo.',
        'actual-reps':'Ripetizioni eseguite','actual-weight':'Peso utilizzato (kg)',
        'next-exercise':'Esercizio Seguente','complete-workout':'Completa Allenamento',
        'workout-done':'Allenamento Completato!','celebrate-msg':'Ottimo lavoro! Hai completato la routine di oggi.',
        'workout-already-done':'Allenamento Completato ✓','back-dash':'Torna alla Dashboard',
        'nav-dash':'Home','nav-train':'Allenamento','nav-prog':'Progressi','nav-prof':'Profilo',
        'start-timer':'Avvia','pause-timer':'Pausa',
        'no-workout':'Inizia un allenamento dalla Dashboard',
        'nutrition':'Nutrizione Raccomandata','bmi-section':'Composizione Corporea',
        'bmi-low':'Sottopeso','bmi-normal':'Normale','bmi-over':'Sovrappeso','bmi-obese':'Obeso',
        'female':'Donna','male':'Uomo',
        'change-routine':'Cambia routine di oggi',
        'rest-title':'Riposo','rest-choose':'Quanto riposi?','skip-rest':'Salta riposo',
        'reconfig-btn':'Riconfigura Il Mio Piano','reconfig-title':'Riconfigura Piano',
        'reconfig-msg':'Questo ti permette di cambiare luogo, attrezzatura, frequenza, giorni e obiettivi. La tua cronologia e le misure vengono mantenute.',
        'next-workout':'Prossimo Allenamento'
    }
};

const firebaseConfig = {
    apiKey: "AIzaSyCCq8vUQRdMNICKEWEtN3ekpjVo4y67PRk",
    authDomain: "gymtrackerv02.firebaseapp.com",
    projectId: "gymtrackerv02",
    storageBucket: "gymtrackerv02.firebasestorage.app",
    messagingSenderId: "962432444627",
    appId: "1:962432444627:web:8c1a6ffd47fada3c95cc26",
    measurementId: "G-0WKR57Q984"
};
